[SIMULATION]
simulation_mode = True
csv_file_simul_path_rollpress= 'D:/PIE/CIM/CSV_SIMUL'

[SLEEP_TIME_SEC]
sleep_time_sec = 2

[USE_CSV]
csv_file_path_rollpress = 'D:/PIE/CIM/CSV/'

csv_rollpress_prefix = 'PREPRESS'
csv_save_solution_folder_name = 'D:/PIE/CIM/ControlResult/'

csv_optimal_solution_filename_prefix = 'AutoControlResult.'
csv_auto_status_filename_prefix = 'AutoStatusResult.'
csv_output_header = 'Time, DeviceId, VariableId, Value\n'

csv_heartbeat = 'heartbeat'
csv_handshake = 'handshake'



[VARNAME] ## variable name in DB 24.01.03


varname_f_os_thickness = 'f_os_thickness'
varname_f_center_thickness = 'f_center_thickness'
varname_f_ds_thickness = 'f_ds_thickness'
varname_s_os_thickness = 's_os_thickness'
varname_s_center_thickness = 's_center_thickness'
varname_s_ds_thickness = 's_ds_thickness'
varname_f_center_os_delta_thickness = 'f_center_os_delta_thickness'
varname_f_center_ds_delta_thickness = 'f_center_ds_delta_thickness'
varname_s_center_os_delta_thickness = 's_center_os_delta_thickness'
varname_s_center_ds_delta_thickness = 's_center_ds_delta_thickness'
varname_rev_control_on = 'rev_control_on'
varname_rev_control_min_speed = 'rev_control_min_speed'
varname_rev_control_min_distance = 'rev_control_min_distance'
varname_rev_control_high_limit = 'rev_control_high_limit'
varname_rev_control_low_limit = 'rev_control_low_limit'
varname_f_thickness_check_count_pv = 'f_thickness_check_count_pv'
varname_s_thickness_check_count_pv = 's_thickness_check_count_pv'
varname_f_thickness_check_count_std = 'f_thickness_check_count_std'
varname_s_thickness_check_count_std = 's_thickness_check_count_std'
varname_f_rev_control_count = 'f_rev_control_count'
varname_s_rev_control_count = 's_rev_control_count'
varname_rollpress_production_distance = 'rollpress_production_distance'
varname_rev_control_thickness_table_1_low = 'rev_control_thickness_table_1_low'
varname_rev_control_thickness_table_1_high = 'rev_control_thickness_table_1_high'
varname_rev_control_thickness_table_2_low = 'rev_control_thickness_table_2_low'
varname_rev_control_thickness_table_2_high = 'rev_control_thickness_table_2_high'
varname_rev_control_thickness_table_3_low = 'rev_control_thickness_table_3_low'
varname_rev_control_thickness_table_3_high = 'rev_control_thickness_table_3_high'
varname_rev_control_thickness_table_4_low = 'rev_control_thickness_table_4_low'
varname_rev_control_thickness_table_4_high = 'rev_control_thickness_table_4_high'
varname_rev_control_thickness_table_5_low = 'rev_control_thickness_table_5_low'
varname_rev_control_thickness_table_5_high = 'rev_control_thickness_table_5_high'
varname_rev_control_thickness_table_6_low = 'rev_control_thickness_table_6_low'
varname_rev_control_thickness_table_6_high = 'rev_control_thickness_table_6_high'
varname_rev_control_thickness_table_lamp_1_f = 'rev_control_thickness_table_lamp_1_f'
varname_rev_control_thickness_table_lamp_1_s = 'rev_control_thickness_table_lamp_1_s'
varname_rev_control_thickness_table_lamp_2_f = 'rev_control_thickness_table_lamp_2_f'
varname_rev_control_thickness_table_lamp_2_s = 'rev_control_thickness_table_lamp_2_s'
varname_rev_control_thickness_table_lamp_3_f = 'rev_control_thickness_table_lamp_3_f'
varname_rev_control_thickness_table_lamp_3_s = 'rev_control_thickness_table_lamp_3_s'
varname_rev_control_thickness_table_lamp_4_f = 'rev_control_thickness_table_lamp_4_f'
varname_rev_control_thickness_table_lamp_4_s = 'rev_control_thickness_table_lamp_4_s'
varname_rev_control_thickness_table_lamp_5_f = 'rev_control_thickness_table_lamp_5_f'
varname_rev_control_thickness_table_lamp_5_s = 'rev_control_thickness_table_lamp_5_s'
varname_rev_control_thickness_table_lamp_6_f = 'rev_control_thickness_table_lamp_6_f'
varname_rev_control_thickness_table_lamp_6_s = 'rev_control_thickness_table_lamp_6_s'
varname_rev_control_thickness_table_sw_1_f = 'rev_control_thickness_table_sw_1_f'
varname_rev_control_thickness_table_sw_1_s = 'rev_control_thickness_table_sw_1_s'
varname_rev_control_thickness_table_sw_2_f = 'rev_control_thickness_table_sw_2_f'
varname_rev_control_thickness_table_sw_2_s = 'rev_control_thickness_table_sw_2_s'
varname_rev_control_thickness_table_sw_3_f = 'rev_control_thickness_table_sw_3_f'
varname_rev_control_thickness_table_sw_3_s = 'rev_control_thickness_table_sw_3_s'
varname_rev_control_thickness_table_sw_4_f = 'rev_control_thickness_table_sw_4_f'
varname_rev_control_thickness_table_sw_4_s = 'rev_control_thickness_table_sw_4_s'
varname_rev_control_thickness_table_sw_5_f = 'rev_control_thickness_table_sw_5_f'
varname_rev_control_thickness_table_sw_5_s = 'rev_control_thickness_table_sw_5_s'
varname_rev_control_thickness_table_sw_6_f = 'rev_control_thickness_table_sw_6_f'
varname_rev_control_thickness_table_sw_6_s = 'rev_control_thickness_table_sw_6_s'
varname_rev_control_thickness_table_val_1_f = 'rev_control_thickness_table_val_1_f'
varname_rev_control_thickness_table_val_1_s = 'rev_control_thickness_table_val_1_s'
varname_rev_control_thickness_table_val_2_f = 'rev_control_thickness_table_val_2_f'
varname_rev_control_thickness_table_val_2_s = 'rev_control_thickness_table_val_2_s'
varname_rev_control_thickness_table_val_3_f = 'rev_control_thickness_table_val_3_f'
varname_rev_control_thickness_table_val_3_s = 'rev_control_thickness_table_val_3_s'
varname_rev_control_thickness_table_val_4_f = 'rev_control_thickness_table_val_4_f'
varname_rev_control_thickness_table_val_4_s = 'rev_control_thickness_table_val_4_s'
varname_rev_control_thickness_table_val_5_f = 'rev_control_thickness_table_val_5_f'
varname_rev_control_thickness_table_val_5_s = 'rev_control_thickness_table_val_5_s'
varname_rev_control_thickness_table_val_6_f = 'rev_control_thickness_table_val_6_f'
varname_rev_control_thickness_table_val_6_s = 'rev_control_thickness_table_val_6_s'
varname_f_rev_control_ds_upper_sv = 'f_rev_control_ds_upper_sv'
varname_f_rev_control_os_upper_sv = 'f_rev_control_os_upper_sv'
varname_f_rev_control_ds_lower_sv = 'f_rev_control_ds_lower_sv'
varname_f_rev_control_os_lower_sv = 'f_rev_control_os_lower_sv'
varname_s_rev_control_ds_upper_sv = 's_rev_control_ds_upper_sv'
varname_s_rev_control_os_upper_sv = 's_rev_control_os_upper_sv'
varname_s_rev_control_ds_lower_sv = 's_rev_control_ds_lower_sv'
varname_s_rev_control_os_lower_sv = 's_rev_control_os_lower_sv'
varname_lot_end = 'lot_end'
varname_f_rev_control_sum = 'f_rev_control_sum'
varname_s_rev_control_sum = 's_rev_control_sum'
varname_f_gap_pid_control_on = 'f_gap_pid_control_on'
varname_s_gap_pid_control_on = 's_gap_pid_control_on'
varname_f_gap_table_control_on = 'f_gap_table_control_on'
varname_s_gap_table_control_on = 's_gap_table_control_on'
varname_f_press_autocontrol_sw = 'f_press_autocontrol_sw'
varname_s_press_autocontrol_sw = 's_press_autocontrol_sw'
varname_f_os_thickness_avg_sv = 'f_os_thickness_avg_sv'
varname_f_ds_thickness_avg_sv = 'f_ds_thickness_avg_sv'
varname_s_os_thickness_avg_sv = 's_os_thickness_avg_sv'
varname_s_ds_thickness_avg_sv = 's_ds_thickness_avg_sv'
varname_f_os_thickness_avg_pv = 'f_os_thickness_avg_pv'
varname_f_ds_thickness_avg_pv = 'f_ds_thickness_avg_pv'
varname_s_os_thickness_avg_pv = 's_os_thickness_avg_pv'
varname_s_ds_thickness_avg_pv = 's_ds_thickness_avg_pv'
varname_f_os_control_start = 'f_os_control_start'
varname_f_ds_control_start = 'f_ds_control_start'
varname_s_os_control_start = 's_os_control_start'
varname_s_ds_control_start = 's_ds_control_start'
varname_f_os_gap_calc_out = 'f_os_gap_calc_out'
varname_f_ds_gap_calc_out = 'f_ds_gap_calc_out'
varname_s_os_gap_calc_out = 's_os_gap_calc_out'
varname_s_ds_gap_calc_out = 's_ds_gap_calc_out'
varname_f_gap_control_sum_std = 'f_gap_control_sum_std'
varname_s_gap_control_sum_std = 's_gap_control_sum_std'
varname_f_gap_control_speed_min = 'f_gap_control_speed_min'
varname_s_gap_control_speed_min = 's_gap_control_speed_min'
varname_f_os_gap_control_count_pv = 'f_os_gap_control_count_pv'
varname_f_ds_gap_control_count_pv = 'f_ds_gap_control_count_pv'
varname_s_os_gap_control_count_pv = 's_os_gap_control_count_pv'
varname_s_ds_gap_control_count_pv = 's_ds_gap_control_count_pv'
varname_f_gap_pid_control_p_gain = 'f_gap_pid_control_p_gain'
varname_s_gap_pid_control_p_gain = 's_gap_pid_control_p_gain'
varname_f_gap_control_min_error_std = 'f_gap_control_min_error_std'
varname_s_gap_control_min_error_std = 's_gap_control_min_error_std'
varname_f_os_gap_thickness_check_count_pv = 'f_os_gap_thickness_check_count_pv'
varname_f_ds_gap_thickness_check_count_pv = 'f_ds_gap_thickness_check_count_pv'
varname_s_os_gap_thickness_check_count_pv = 's_os_gap_thickness_check_count_pv'
varname_s_ds_gap_thickness_check_count_pv = 's_ds_gap_thickness_check_count_pv'
varname_fds_pos_val = 'fds_pos_val'
varname_fws_pos_val = 'fws_pos_val'
varname_sds_pos_val = 'sds_pos_val'
varname_sws_pos_val = 'sws_pos_val'
varname_f_pos_interlock = 'f_pos_interlock'
varname_s_pos_interlock = 's_pos_interlock'
varname_fds_under_roll_pv = 'fds_under_roll_pv'
varname_fws_under_roll_pv = 'fws_under_roll_pv'
varname_sds_under_roll_pv = 'sds_under_roll_pv'
varname_sws_under_roll_pv = 'sws_under_roll_pv'
varname_fds_under_roll_sv = 'fds_under_roll_sv'
varname_fws_under_roll_sv = 'fws_under_roll_sv'
varname_sds_under_roll_sv = 'sds_under_roll_sv'
varname_sws_under_roll_sv = 'sws_under_roll_sv'
varname_speed_pv = 'speed_pv'
varname_a_bobin_type = 'a_bobin_type'
varname_b_bobin_type = 'b_bobin_type'
varname_a_bobin_model_1 = 'a_bobin_model_1'
varname_a_bobin_model_2 = 'a_bobin_model_2'
varname_a_bobin_model_3 = 'a_bobin_model_3'
varname_a_bobin_model_4 = 'a_bobin_model_4'
varname_a_bobin_model_5 = 'a_bobin_model_5'
varname_a_bobin_model_6 = 'a_bobin_model_6'
varname_a_bobin_model_7 = 'a_bobin_model_7'
varname_a_bobin_model_8 = 'a_bobin_model_8'
varname_b_bobin_model_1 = 'b_bobin_model_1'
varname_b_bobin_model_2 = 'b_bobin_model_2'
varname_b_bobin_model_3 = 'b_bobin_model_3'
varname_b_bobin_model_4 = 'b_bobin_model_4'
varname_b_bobin_model_5 = 'b_bobin_model_5'
varname_b_bobin_model_6 = 'b_bobin_model_6'
varname_b_bobin_model_7 = 'b_bobin_model_7'
varname_b_bobin_model_8 = 'b_bobin_model_8'
varname_fds_rev_back_up = 'fds_rev_back_up'
varname_fws_rev_back_up = 'fws_rev_back_up'
varname_sds_rev_back_up = 'sds_rev_back_up'
varname_sws_rev_back_up = 'sws_rev_back_up'
varname_fds_rev_pv = 'fds_rev_pv'
varname_fws_rev_pv = 'fws_rev_pv'
varname_sds_rev_pv = 'sds_rev_pv'
varname_sws_rev_pv = 'sws_rev_pv'
varname_fds_load_cell_pv = 'fds_load_cell_pv'
varname_fws_load_cell_pv = 'fws_load_cell_pv'
varname_sds_load_cell_pv = 'sds_load_cell_pv'
varname_sws_load_cell_pv = 'sws_load_cell_pv'
varname_loadcell_zero_set = 'loadcell_zero_set'
varname_thickness_alarm = 'thickness_alarm'
varname_f_pre_press_complete = 'f_pre_press_complete'
varname_s_pre_press_complete = 's_pre_press_complete'
varname_pre_press_on = 'pre_press_on'
varname_pre_press_stop = 'pre_press_stop'
varname_run = 'run'
varname_low = 'low'
varname_f_actual_run = 'f_actual_run'
varname_s_actual_run = 's_actual_run'
varname_f_actual_low = 'f_actual_low'
varname_s_actual_low = 's_actual_low'
varname_f_gap_control_upper_limit = 'f_gap_control_upper_limit'
varname_f_gap_control_lower_limit = 'f_gap_control_lower_limit'
varname_control_freq = 'control_freq'
varname_f_gap_control_complete_time = 'f_gap_control_complete_time'
varname_s_gap_control_complete_time = 's_gap_control_complete_time'
varname_f_interlock = 'f_interlock'
varname_s_interlock = 's_interlock'
varname_f_gap_control_up = 'f_gap_control_up'
varname_f_gap_control_down = 'f_gap_control_down'
varname_s_gap_control_up = 's_gap_control_up'
varname_s_gap_control_down = 's_gap_control_down'
varname_f_range = 'f_range'
varname_s_range = 's_range'
varname_f_gap_control_offset_high = 'f_gap_control_offset_high'
varname_f_gap_control_offset_low = 'f_gap_control_offset_low'
varname_s_gap_control_offset_high = 's_gap_control_offset_high'
varname_s_gap_control_offset_low = 's_gap_control_offset_low'
varname_f_gap_control_mode_both = 'f_gap_control_mode_both'
varname_f_gap_control_mode_ds = 'f_gap_control_mode_ds'
varname_f_gap_control_mode_os = 'f_gap_control_mode_os'
varname_s_gap_control_mode_both = 's_gap_control_mode_both'
varname_s_gap_control_mode_ds = 's_gap_control_mode_ds'
varname_s_gap_control_mode_os = 's_gap_control_mode_os'
varname_f_gap_control_additional_ds = 'f_gap_control_additional_ds'
varname_f_gap_control_additional_os = 'f_gap_control_additional_os'
varname_s_gap_control_additional_ds = 's_gap_control_additional_ds'
varname_s_gap_control_additional_os = 's_gap_control_additional_os'
varname_f_gap_control_range_lower = 'f_gap_control_range_lower'
varname_s_gap_control_range_lower = 's_gap_control_range_lower'
varname_f_gap_control_range_upper = 'f_gap_control_range_upper'
varname_s_gap_control_range_upper = 's_gap_control_range_upper'
varname_f_window_popup_confirm = 'f_window_popup_confirm'
varname_f_window_popup_number = 'f_window_popup_number'
varname_s_window_popup_confirm = 's_window_popup_confirm'
varname_s_window_popup_number = 's_window_popup_number'
varname_pre_press_time_para = 'pre_press_time_para'
varname_f_pre_press_stop_time_min = 'f_pre_press_stop_time_min'
varname_s_pre_press_stop_time_min = 's_pre_press_stop_time_min'
varname_f_load_cell_back_up = 'f_load_cell_back_up'
varname_s_load_cell_back_up = 's_load_cell_back_up'
varname_f_control_inch = 'f_control_inch'
varname_s_control_inch = 's_control_inch'
varname_control_inch = 'control_inch'
varname_pre_press_rev_control_t1 = 'pre_press_rev_control_t1'
varname_pre_press_rev_control_t2 = 'pre_press_rev_control_t2'
varname_pre_press_rev_control_t3 = 'pre_press_rev_control_t3'
varname_pre_press_rev_control_t4 = 'pre_press_rev_control_t4'
varname_f_pre_press_rev_control_val1 = 'f_pre_press_rev_control_val1'
varname_s_pre_press_rev_control_val1 = 's_pre_press_rev_control_val1'
varname_f_pre_press_rev_control_val2 = 'f_pre_press_rev_control_val2'
varname_s_pre_press_rev_control_val2 = 's_pre_press_rev_control_val2'
varname_f_pre_press_rev_control_val3 = 'f_pre_press_rev_control_val3'
varname_s_pre_press_rev_control_val3 = 's_pre_press_rev_control_val3'
varname_f_pre_press_rev_control_val4 = 'f_pre_press_rev_control_val4'
varname_s_pre_press_rev_control_val4 = 's_pre_press_rev_control_val4'




####################################재조건조정 control result####################################


## 항시 update되는 변수(인터락,로드셀합산값)
varname_prepress_alwayson_outputs = f_interlock,s_interlock,f_range,s_range

##Backup 변수 

varname_prepress_backup_outputs = f_load_cell_back_up,f_gap_control_range_upper,f_gap_control_range_lower,s_load_cell_back_up,s_gap_control_range_upper,s_gap_control_range_lower

varname_f_prepress_backup_outputs =  f_load_cell_back_up,f_gap_control_range_upper,f_gap_control_range_lower
varname_s_prepress_backup_outputs = s_load_cell_back_up,s_gap_control_range_upper,s_gap_control_range_lower



##제어모드 변경(CONFIG PARA내 TYPE변경에 따라 적용) 

varname_prepress_control_mode_change=f_gap_control_mode_both,f_gap_control_mode_ds,f_gap_control_mode_os,s_gap_control_mode_both,s_gap_control_mode_ds,s_gap_control_mode_os
varname_f_prepress_control_mode_change=f_gap_control_mode_both,f_gap_control_mode_ds,f_gap_control_mode_os
varname_s_prepress_control_mode_change=s_gap_control_mode_both,s_gap_control_mode_ds,s_gap_control_mode_os

######low or run시점에 1회 update해주는 변수(제어인치 , 역압) 

varname_f_prepress_hmi2plc_outputs=f_control_inch,f_rev_control_os_upper_sv,f_rev_control_ds_upper_sv,f_rev_control_os_lower_sv,f_rev_control_ds_lower_sv

varname_s_prepress_hmi2plc_outputs=s_control_inch,s_rev_control_os_upper_sv,s_rev_control_ds_upper_sv,s_rev_control_os_lower_sv,s_rev_control_ds_lower_sv


##재조건조정 실행(제어인치, gap up&down 신호, window popup&number) 

varname_prepress_control_outputs =f_control_inch,s_control_inch,f_gap_control_up,f_gap_control_down,s_gap_control_up,s_gap_control_down,f_window_popup_confirm,f_window_popup_number,s_window_popup_confirm,s_window_popup_number
varname_f_prepress_control_outputs = f_control_inch,f_gap_control_up,f_gap_control_down,f_window_popup_confirm,f_window_popup_number
varname_s_prepress_control_outputs = s_control_inch,s_gap_control_up,s_gap_control_down,s_window_popup_confirm,s_window_popup_number

##재조건조정완료(완료신호,설비시작신호, 인치값 원복) 

varname_f_prepress_complete_outputs=f_pre_press_complete,f_actual_run,f_actual_low,f_control_inch,f_window_popup_confirm,f_window_popup_number,varname_f_prepress_stop_time_min
varname_s_prepress_complete_outputs=s_pre_press_complete,s_actual_run,s_actual_low,s_control_inch,s_window_popup_confirm,s_window_popup_number,varname_s_prepress_stop_time_min


##초기화 변수(선압완료신호) 
varname_prepress_initialize_outputs=f_pre_press_complete,s_pre_press_complete,varname_f_prepress_stop_time_min,varname_s_prepress_stop_time_min


##hmi update 변수(항시 입력)
varname_hmi_update_params=gap_control_lower_limit,gap_control_upper_limit



####################################역압 control result#####################################


##hmi lamp update 변수
varname_f_revcontrol_lamps=rev_control_thickness_table_lamp_1_f,rev_control_thickness_table_lamp_2_f,rev_control_thickness_table_lamp_3_f,rev_control_thickness_table_lamp_4_f,rev_control_thickness_table_lamp_5_f,rev_control_thickness_table_lamp_6_f

varname_s_revcontrol_lamps=rev_control_thickness_table_lamp_1_s,rev_control_thickness_table_lamp_2_s,rev_control_thickness_table_lamp_3_s,rev_control_thickness_table_lamp_4_s,rev_control_thickness_table_lamp_5_s,rev_control_thickness_table_lamp_6_s

#hmi update 변수
varname_revcontrol_hmi_update_params=f_center_os_delta_thickness,f_center_ds_delta_thickness,s_center_os_delta_thickness,s_center_ds_delta_thickness


##역압 자동보정 실행
varname_f_revcontrol_outputs=f_rev_control_os_upper_sv,f_rev_control_ds_upper_sv,f_rev_control_os_lower_sv,f_rev_control_ds_lower_sv,f_rev_control_count,f_rev_control_sum,f_thickness_check_count_pv
varname_s_revcontrol_outputs=s_rev_control_os_upper_sv,s_rev_control_ds_upper_sv,s_rev_control_os_lower_sv,s_rev_control_ds_lower_sv,s_rev_control_count,s_rev_control_sum,s_thickness_check_count_pv

##lot end 초기화
varname_f_revcontrol_initialize_outputs = f_rev_control_count,f_rev_control_sum,f_thickness_check_count_pv
varname_s_revcontrol_initialize_outputs = s_rev_control_count,s_rev_control_sum,s_thickness_check_count_pv


####################################gap control result#####################################

##gap 자동보정 실행
varname_f_os_gapcontrol_outputs=f_os_gap_calc_out,f_os_gap_control_count_pv
varname_f_ds_gapcontrol_outputs=f_ds_gap_calc_out,f_ds_gap_control_count_pv
varname_s_os_gapcontrol_outputs=s_os_gap_calc_out,s_os_gap_control_count_pv
varname_s_ds_gapcontrol_outputs=s_ds_gap_calc_out,s_ds_gap_control_count_pv

varname_f_os_gapcontrol_reset=f_os_gap_calc_out
varname_f_ds_gapcontrol_reset=f_ds_gap_calc_out
varname_s_os_gapcontrol_reset=s_os_gap_calc_out
varname_s_ds_gapcontrol_reset=s_ds_gap_calc_out

##초기화
varname_f_gapcontrol_initialize_outputs=f_os_gap_control_count_pv,f_ds_gap_control_count_pv,f_os_gap_thickness_check_count_pv,f_ds_gap_thickness_check_count_pv,f_os_gap_calc_out,f_ds_gap_calc_out
varname_s_gapcontrol_initialize_outputs=s_os_gap_control_count_pv,s_ds_gap_control_count_pv,s_os_gap_thickness_check_count_pv,s_ds_gap_thickness_check_count_pv,s_os_gap_calc_out,s_ds_gap_calc_out


[SETTINGS]
revVal = 30

## table names in DB
[TABLE_NAME]
table_name_rollpress_data = a_prepress_data

[NEW]
current_usable_time = 60 # sec
plc_dict_name = 'prepress'
plc_recent_time = 10
