[CONTROL_CONFIG]

##재조건조정
machine_num = 1 ##설비 종류 번호 (1-CIS, 2-PNT)

# 0 : off, 1 : on
bobin_model_check_mode = 0
# ( 0: 생략 , 1: HMI에서 OS,DS 수치입력받아서 GAP 조정)
gap_control_after_complete_type = 1 
  
# 로드셀 역압 영점 setting
loadcell_zero_set = 15 


##등속구간

#역압
unwinder_distance_param = 11

#gap
low_speed_mode_use = 1

f_roll_to_thicness_distance = 10
f_thickness_indicator_swing_time = 7
s_roll_to_thicness_distance = 10
s_thickness_indicator_swing_time = 7

[CONTROLLIMIT]

#gap 누적값 상하한
gap_control_lower_limit = -50 
gap_control_upper_limit = 50 


[HMI_PARAM_LIMIT]
control_freq_min = 2
f_gap_control_offset_high_min = 0
f_gap_control_offset_low_min = 0
s_gap_control_offset_high_min = 0
s_gap_control_offset_low_min = 0

control_inch_min = 0.5
control_inch_max = 5

[ALARM_PARAM]
#역압 delta값 limit
f_delta_control_val_limit = 30
s_delta_control_val_limit = 30

[NEW]
plc_recent_time = 10

[LOG] ## debug, operation, critical level분류
level = "debug"

